# Generated by Django 4.2.2 on 2023-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Employee Id')),
                ('EmployeeName', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('Department', models.CharField(max_length=100, verbose_name='Department')),
                ('DateOfJoining', models.DateField(verbose_name='Date of Joining')),
                ('PhotoFileName', models.CharField(default=None, max_length=100, verbose_name='Photo File Name')),
            ],
        ),
    ]
